PR Entregable 2 - Salvador Medrano
WIZEACADEMY-BAZ/BAZJAVA_BLOQUE2 pull request #39
Opened 2022-11-04 17:27 UTC by SalvadorMedrano

2022-11-09 01:23 UTC, Wizeline-GerardoRuiz requested changes

2022-11-09 01:23 UTC, Wizeline-GerardoRuiz commented on Salvador_Medrano_Romero/Entregable 2/practicajava/practicajava/src/main/java/com/wizeline/gradle/practicajava/PracticajavaApplication.java
> +public class PracticajavaApplication extends Thread{
La herencia que haces de Thread hay que implementarla para considerarla completada

2022-11-09 01:23 UTC, Wizeline-GerardoRuiz commented on Salvador_Medrano_Romero/Entregable 2/practicajava/practicajava/src/main/java/com/wizeline/gradle/practicajava/PracticajavaApplication.java
> +//				Optional<String> Optionalnombre = getParameterValue(params, "name");
Esto debe estar implementado en un endpoint para considerarlo completado

2022-11-09 01:23 UTC, Wizeline-GerardoRuiz commented on Salvador_Medrano_Romero/Entregable 2/practicajava/practicajava/src/main/java/com/wizeline/gradle/practicajava/PracticajavaApplication.java
> +//	                Cipher cipher = null;
Esto hay que implementarlo en un endpoint para considerarlo como entregado

2022-11-09 01:23 UTC, Wizeline-GerardoRuiz commented on Salvador_Medrano_Romero/Entregable 2/practicajava/practicajava/src/main/java/com/wizeline/gradle/practicajava/controller/BankingAccountController.java
> +public class BankingAccountController {
Aprovecha y define un endpoint con put (@PutMapping) para considerar ese punto completado

2022-11-09 01:23 UTC, Wizeline-GerardoRuiz commented on Salvador_Medrano_Romero/Entregable 2/practicajava/practicajava/src/main/resources/application.properties
> +info.app.name=LearningJava API
Si incluyes aqui la definicion de tus Actuators e incluyes la dependencia en tu build.gradle puedes considerar ese punto completado

2022-11-09 22:44 UTC, SalvadorMedrano commented on Salvador_Medrano_Romero/Entregable 2/practicajava/practicajava/src/main/java/com/wizeline/gradle/practicajava/PracticajavaApplication.java
> +//				Optional<String> Optionalnombre = getParameterValue(params, "name");
Se implementa Optional en la clase CursoServiceImpl método obtenerCalificaciones

2022-11-09 23:49 UTC, SalvadorMedrano commented on Salvador_Medrano_Romero/Entregable 2/practicajava/practicajava/src/main/java/com/wizeline/gradle/practicajava/PracticajavaApplication.java
> +public class PracticajavaApplication extends Thread{
Se implementa uso de hilos en la clase CursoServiceImpl

2022-11-09 23:50 UTC, SalvadorMedrano commented on Salvador_Medrano_Romero/Entregable 2/practicajava/practicajava/src/main/java/com/wizeline/gradle/practicajava/PracticajavaApplication.java
> +//	                Cipher cipher = null;
Se implementa cifrado en la clase CursoServiceImpl método guardaEstudiantes que invoca a su vez el método cifrar

2022-11-09 23:51 UTC, SalvadorMedrano commented on Salvador_Medrano_Romero/Entregable 2/practicajava/practicajava/src/main/java/com/wizeline/gradle/practicajava/controller/BankingAccountController.java
> +public class BankingAccountController {
Se implementa endpoint con verbo PUT para actualizar las calificaciones de un estudiante

2022-11-09 23:51 UTC, SalvadorMedrano commented on Salvador_Medrano_Romero/Entregable 2/practicajava/practicajava/src/main/resources/application.properties
> +info.app.name=LearningJava API
Se implementa Actuators con sus endpoints correspondientes

2022-11-10 00:36 UTC, Wizeline-GerardoRuiz approved these changes
LGTM 👍

2022-11-10 00:36 UTC, merged