se sube lo correspondiente el entregable 2
WIZEACADEMY-BAZ/BAZJAVA_BLOQUE2 pull request #42
Opened 2022-11-07 23:04 UTC by CristianEJimenez

2022-11-09 02:42 UTC, Wizeline-GerardoRuiz requested changes

2022-11-09 02:42 UTC, Wizeline-GerardoRuiz commented on Cristian-Jimenez/Entregable2/learningjavagmaven/src/main/java/com/wizeline/maven/learningjavagmaven/LearningjavagmavenApplication.java
> +public class LearningjavagmavenApplication extends Thread {
Hay que implementar esta herencia con comportamiento y logica para considerarlo entregado

2022-11-09 02:42 UTC, Wizeline-GerardoRuiz commented on Cristian-Jimenez/Entregable2/learningjavagmaven/learningjavagmaven/.gitignore
> +HELP.md
Desde aqui se ve el codigo duplicado, por favor depura lo que si debe ir y lo que no

2022-11-09 02:42 UTC, Wizeline-GerardoRuiz commented on Cristian-Jimenez/Entregable2/learningjavagmaven/learningjavagmaven/src/main/java/com/wizeline/maven/learningjavagmaven/controller/BankingAccountController.java
> +public class BankingAccountController {
Aqui puedes aprovechar y agregar un endpoint PUT (@PutMapping) para considerar ese punto entregado

2022-11-09 23:40 UTC, CristianEJimenez commented on Cristian-Jimenez/Entregable2/learningjavagmaven/src/main/java/com/wizeline/maven/learningjavagmaven/LearningjavagmavenApplication.java
> +public class LearningjavagmavenApplication extends Thread {
Se implementa en un  nuevo método llamado createUser y se complementa con el postman

2022-11-09 23:40 UTC, CristianEJimenez commented on Cristian-Jimenez/Entregable2/learningjavagmaven/learningjavagmaven/.gitignore
> +HELP.md
Se quita la duplicidad de archivos y queda correctamente

2022-11-09 23:40 UTC, CristianEJimenez commented on Cristian-Jimenez/Entregable2/learningjavagmaven/learningjavagmaven/src/main/java/com/wizeline/maven/learningjavagmaven/controller/BankingAccountController.java
> +public class BankingAccountController {
se Agrega el EndPoint y se revisa pon Postman, se hace un cambio en el archivo del potsman

2022-11-10 00:30 UTC, gruizest approved these changes
LGTM 👍

2022-11-10 00:31 UTC, Wizeline-GerardoRuiz approved these changes
LGTM 👍

2022-11-10 00:31 UTC, merged