Alejandro ramirez entregable2
WIZEACADEMY-BAZ/BAZJAVA_BLOQUE2 pull request #56
Opened 2022-11-08 23:41 UTC by aramirex

2022-11-09 02:12 UTC, Wizeline-GerardoRuiz requested changes

2022-11-09 02:12 UTC, Wizeline-GerardoRuiz commented on Alejandro_Ramirez_Flores/Entregable2/.gitignore.txt
> +# Ignora el archivo LinkcriteriosDeEvaluacion.txt
Archivo basura, no debe tener extension (.txt) por lo que hay que borrarlo

2022-11-09 02:12 UTC, Wizeline-GerardoRuiz commented on Alejandro_Ramirez_Flores/Entregable2/learningjavagradle/.gitignore
> +!**/src/test/**/bin/
Este archivo debe estar al nivel principal de tu proyecto, hay que moverlo

2022-11-09 02:12 UTC, Wizeline-GerardoRuiz commented on Alejandro_Ramirez_Flores/Entregable2/learningjavagradle/build.gradle
> +//	implementation 'org.springframework.boot:spring-boot-starter-batch'
Estas dependencias hay que incluirlas en el proyecto y configurarlas para realizar la entrega complementaria

2022-11-09 02:12 UTC, Wizeline-GerardoRuiz commented on Alejandro_Ramirez_Flores/Entregable2/learningjavagradle/src/main/java/com/wizeline/gradle/learningjavagrade/client/AccountsJSONClient.java
> +@FeignClient(value="getAccountsClient", url="https://jsonplaceholder.typicode.com/")
Incluiste codigo que no corresponde con la entrega, hay que limpiar la estructura del proyecto

2022-11-09 02:12 UTC, Wizeline-GerardoRuiz commented on Alejandro_Ramirez_Flores/Entregable2/learningjavagradle/src/main/java/com/wizeline/gradle/learningjavagradle/batch/UserJob.java
> +package com.wizeline.gradle.learningjavagradle.batch;
Incluiste codigo que no corresponde con la entrega, hay que limpiar la estructura del proyecto

2022-11-09 02:12 UTC, Wizeline-GerardoRuiz commented on Alejandro_Ramirez_Flores/Entregable2/learningjavagradle/src/main/java/com/wizeline/gradle/learningjavagradle/configuration/BatchConfiguration.java
> +package com.wizeline.gradle.learningjavagradle.configuration;
Incluiste codigo que no corresponde con la entrega, hay que limpiar la estructura del proyecto

2022-11-09 02:12 UTC, Wizeline-GerardoRuiz commented on Alejandro_Ramirez_Flores/Entregable2/learningjavagradle/src/main/java/com/wizeline/gradle/learningjavagradle/configuration/SecurityConfig.java
> +@EnableGlobalMethodSecurity(prePostEnabled = true)
Hay que terminar la integracion de esta funcionalidad a la aplicacion incluyendo las anotaciones correspondientes (@PreAuthorize)

2022-11-09 02:12 UTC, Wizeline-GerardoRuiz commented on Alejandro_Ramirez_Flores/Entregable2/learningjavagradle/src/main/java/com/wizeline/gradle/learningjavagradle/LearningjavagradleApplication.java
> +@SpringBootApplication(exclude = {SecurityAutoConfiguration.class})
Hay que quitar esta exclusion de la anotacion para terminar la integracion de Spring Security

2022-11-09 02:12 UTC, Wizeline-GerardoRuiz commented on Alejandro_Ramirez_Flores/Entregable2/learningjavagradle/src/main/resources/application.properties
> +
Hay que colocar aqui las propiedades que configuran a los Actuators para considerarlo entregado

2022-11-09 02:12 UTC, Wizeline-GerardoRuiz commented on Alejandro_Ramirez_Flores/Entregable2/learningjavagradle/src/main/java/com/wizeline/gradle/learningjavagradle/controller/BankingAccountController.java
> +public class BankingAccountController {
Aqui podrias aprovechar para incluir un metodo PUT en tu aplicacion (@PutMapping)

2022-11-09 02:12 UTC, Wizeline-GerardoRuiz commented on Alejandro_Ramirez_Flores/Entregable2/learningjavagradle/src/main/java/com/wizeline/gradle/learningjavagradle/LearningjavagradleApplication.java
> +public class LearningjavagradleApplication extends Thread {
Hay que darle comportamiento y uso a esta herencia para considerarla como entregada

2022-11-10 22:42 UTC, aramirex commented on Alejandro_Ramirez_Flores/Entregable2/.gitignore.txt
> +# Ignora el archivo LinkcriteriosDeEvaluacion.txt
Archivo eliminado

2022-11-10 22:44 UTC, aramirex commented on Alejandro_Ramirez_Flores/Entregable2/learningjavagradle/.gitignore
> +!**/src/test/**/bin/
El archivo esta en el nivel principal

2022-11-10 22:46 UTC, aramirex commented on Alejandro_Ramirez_Flores/Entregable2/learningjavagradle/build.gradle
> +//	implementation 'org.springframework.boot:spring-boot-starter-batch'
Agregue la dependencia Correspondiente y funcional en una linea mas abajo, procedo a eliminar el código comentado

2022-11-10 23:15 UTC, aramirex commented on Alejandro_Ramirez_Flores/Entregable2/learningjavagradle/src/main/java/com/wizeline/gradle/learningjavagrade/client/AccountsJSONClient.java
> +@FeignClient(value="getAccountsClient", url="https://jsonplaceholder.typicode.com/")
Corresponde al entregable 3, no es posible quitarlo, es para la revisión siguiente.

2022-11-10 23:16 UTC, aramirex commented on Alejandro_Ramirez_Flores/Entregable2/learningjavagradle/src/main/java/com/wizeline/gradle/learningjavagradle/batch/UserJob.java
> +package com.wizeline.gradle.learningjavagradle.batch;
Corresponde al entregable 3, no es posible quitarlo, es para la revisión posterior.

2022-11-10 23:23 UTC, aramirex commented on Alejandro_Ramirez_Flores/Entregable2/learningjavagradle/src/main/java/com/wizeline/gradle/learningjavagradle/configuration/SecurityConfig.java
> +@EnableGlobalMethodSecurity(prePostEnabled = true)
la integración de la funcionalidad esta terminada

2022-11-10 23:32 UTC, aramirex commented on Alejandro_Ramirez_Flores/Entregable2/learningjavagradle/src/main/java/com/wizeline/gradle/learningjavagradle/LearningjavagradleApplication.java
> +@SpringBootApplication(exclude = {SecurityAutoConfiguration.class})
Se elimina la exclusión para la anotación @SpringBootApplication

2022-11-10 23:33 UTC, aramirex commented on Alejandro_Ramirez_Flores/Entregable2/learningjavagradle/src/main/resources/application.properties
> +
Se completaron las propiedades para realizar el ejercicio correspondiente(Actuators).

2022-11-10 23:36 UTC, aramirex commented on Alejandro_Ramirez_Flores/Entregable2/learningjavagradle/src/main/java/com/wizeline/gradle/learningjavagradle/LearningjavagradleApplication.java
> +public class LearningjavagradleApplication extends Thread {
Se elimino, esta herencia.

2022-11-10 23:47 UTC, aramirex commented on Alejandro_Ramirez_Flores/Entregable2/learningjavagradle/src/main/java/com/wizeline/gradle/learningjavagradle/controller/BankingAccountController.java
> +public class BankingAccountController {
No se incluyo método PUT a la clase BankingAccountController, ya que se agrego una clase  con el nombre CuentaNomController , se incluyen los métodos correspondientes Get, Post, Put, Delete, derivado de la clase CuentaNomServiceImpl e interfaz CuentaNomService.

2022-11-11 01:08 UTC, gruizest approved these changes
LGTM 👍

2022-11-11 01:10 UTC, Wizeline-GerardoRuiz approved these changes
LGTM 👍

2022-11-11 01:10 UTC, merged