Se sube entregable3
WIZEACADEMY-BAZ/BAZJAVA_BLOQUE2 pull request #67
Opened 2022-11-21 20:54 UTC by ecedillocs

2022-11-23 02:15 UTC, Wizeline-GerardoRuiz requested changes

2022-11-23 02:15 UTC, Wizeline-GerardoRuiz commented on Eduardo_Antonio_Cedillo_Segovia/Entregable3/LoadBalancer/src/main/java/com/codeusingjava/LoadBalancerApplication.java
> +@SpringBootApplication(scanBasePackages= {
Esta aplicación (LoadBalancer) no debe ser parte de la entrega final, hay que eliminarla para considerarla válida

2022-11-23 02:15 UTC, Wizeline-GerardoRuiz commented on Eduardo_Antonio_Cedillo_Segovia/Entregable3/learningjavamaven/DockerFile
> +FROM openjdk:11
El nombre del archivo está mal, hay que corregirlo

2022-11-23 02:15 UTC, Wizeline-GerardoRuiz commented on Eduardo_Antonio_Cedillo_Segovia/Entregable3/learningjavamaven/DockerFile.txt
> +FROM openjdk:11
Este archivo es inválido, hay que eliminarlo

2022-11-23 02:15 UTC, Wizeline-GerardoRuiz commented on Eduardo_Antonio_Cedillo_Segovia/Entregable3/learningjavamaven/src/test/java/com/wizeline/maven/learningjavamaven/controller/UserControllerTest.java
> +        ResponseDTO response = new ResponseDTO();
Hay que incluir mensajes en la consola usando Logger para indicar los pasos del ciclo de vida del caso de prueba

2022-11-23 02:15 UTC, Wizeline-GerardoRuiz commented on Eduardo_Antonio_Cedillo_Segovia/Entregable3/learningjavamaven/src/test/java/com/wizeline/maven/learningjavamaven/controller/UserControllerTest.java
> +public class UserControllerTest {
Hay que incluir más pruebas para el Happy Path y pruebas que contemplen Edge Cases de tu aplicación

2022-11-23 02:15 UTC, Wizeline-GerardoRuiz commented on Eduardo_Antonio_Cedillo_Segovia/Entregable3/learningjavamaven/pom.xml
> +		<plugins>
Hay que incluir el plugin de JaCoCo o de SonarCloud y configurarlos para considerarlo completado

2022-11-25 17:11 UTC, ecedillocs commented on Eduardo_Antonio_Cedillo_Segovia/Entregable3/LoadBalancer/src/main/java/com/codeusingjava/LoadBalancerApplication.java
> +@SpringBootApplication(scanBasePackages= {
Ya se elimino en la ultima entrega

2022-11-25 17:12 UTC, ecedillocs commented on Eduardo_Antonio_Cedillo_Segovia/Entregable3/learningjavamaven/DockerFile
> +FROM openjdk:11
Se corrigio el nombre del archivo

2022-11-25 17:12 UTC, ecedillocs commented on Eduardo_Antonio_Cedillo_Segovia/Entregable3/learningjavamaven/DockerFile.txt
> +FROM openjdk:11
El archivo se ha eliminado

2022-11-25 17:12 UTC, ecedillocs commented on Eduardo_Antonio_Cedillo_Segovia/Entregable3/learningjavamaven/src/test/java/com/wizeline/maven/learningjavamaven/controller/UserControllerTest.java
> +        ResponseDTO response = new ResponseDTO();
Se incluyeron mensajes en la consola con Logger

2022-11-25 17:13 UTC, ecedillocs commented
Se corrigieron los puntos mencionados. gracias

2022-11-25 21:18 UTC, Wizeline-GerardoRuiz approved these changes
LGTM 👍

2022-11-25 21:18 UTC, merged