entregable3 21/11/22 17_15
WIZEACADEMY-BAZ/BAZJAVA_BLOQUE2 pull request #70
Opened 2022-11-21 23:19 UTC by CristianEJimenez

entregable3

2022-11-23 01:34 UTC, Wizeline-GerardoRuiz requested changes

2022-11-23 01:34 UTC, Wizeline-GerardoRuiz commented on Cristian-Jimenez/entregable3/learningjavagmaven/src/test/java/com/wizeline/maven/learningjavagmaven/LearningjavagmavenApplicationTests.java
> +class LearningjavagmavenApplicationTests {
Abre una nueva carpeta dentro de "test" donde esté contenida toda la lógica de prueba de tus operaciones CRUD, de preferencia que se llame "repository"

2022-11-23 01:34 UTC, Wizeline-GerardoRuiz commented on Cristian-Jimenez/entregable3/learningjavagmaven/src/test/java/com/wizeline/maven/learningjavagmaven/controller/BankingAccountControllerTest.java
> +        response = bankingController.deleteAccounts();
En todos tus casos de prueba hace falta usar Logger para reportar cada paso de ejecución en el ciclo de vida de dicha prueba

2022-11-23 01:34 UTC, Wizeline-GerardoRuiz commented on Cristian-Jimenez/entregable3/learningjavagmaven/pom.xml
> +							<artifactId>lombok</artifactId>
Aquí debes incluir el plugin de JaCoCo y su configuración en caso de que quieras usar dicha herramienta de cobertura de pruebas

2022-11-24 00:40 UTC, CristianEJimenez commented on Cristian-Jimenez/entregable3/learningjavagmaven/src/test/java/com/wizeline/maven/learningjavagmaven/LearningjavagmavenApplicationTests.java
> +class LearningjavagmavenApplicationTests {
se implementan pruebas CRUD en la carpeta indicada

2022-11-24 00:40 UTC, CristianEJimenez commented on Cristian-Jimenez/entregable3/learningjavagmaven/src/test/java/com/wizeline/maven/learningjavagmaven/controller/BankingAccountControllerTest.java
> +        response = bankingController.deleteAccounts();
se incorporan los comentarios requeridos

2022-11-24 00:41 UTC, CristianEJimenez commented on Cristian-Jimenez/entregable3/learningjavagmaven/pom.xml
> +							<artifactId>lombok</artifactId>
por falta de tiempo no se pudo incluir

2022-11-24 01:10 UTC, gruizest approved these changes
LGTM 👍

2022-11-24 01:12 UTC, Wizeline-GerardoRuiz approved these changes
LGTM 👍

2022-11-24 01:12 UTC, merged