Salvador Medrano Romero - Entregable 3
WIZEACADEMY-BAZ/BAZJAVA_BLOQUE2 pull request #77
Opened 2022-11-21 23:57 UTC by SalvadorMedrano

2022-11-23 01:30 UTC, Wizeline-GerardoRuiz requested changes

2022-11-23 01:30 UTC, Wizeline-GerardoRuiz commented on Salvador_Medrano_Romero/Entregable 2/practicajava/practicajava/build.gradle
>  	implementation 'org.springframework.boot:spring-boot-starter-web'
Ya que tu proyecto es Gradle, tu Dockerfile debe tomar el proyecto desde "build" y no desde "target"

2022-11-23 01:30 UTC, Wizeline-GerardoRuiz commented on Salvador_Medrano_Romero/Entregable 2/practicajava/practicajava/build.gradle
>  }
También debes incluir el plugin de JaCoCo en caso de que quieras implementar esa herramienta de cobertura de pruebas

2022-11-23 01:30 UTC, Wizeline-GerardoRuiz commented on Salvador_Medrano_Romero/README.md
>      > La carpeta practicaJava contiene el código trabajado
Falta la carpeta "test" donde deben estar contenidas todas tus pruebas debidamente documentadas con logs y usando Mockito para considerar la parte de pruebas completada

2022-11-24 02:10 UTC, SalvadorMedrano commented on Salvador_Medrano_Romero/Entregable 2/practicajava/practicajava/build.gradle
>  	implementation 'org.springframework.boot:spring-boot-starter-web'
Se actualiza configuración para gradle

2022-11-24 02:11 UTC, SalvadorMedrano commented on Salvador_Medrano_Romero/Entregable 2/practicajava/practicajava/build.gradle
>  }
Se implementa JaCoCo

2022-11-24 04:05 UTC, SalvadorMedrano commented on Salvador_Medrano_Romero/README.md
>      > La carpeta practicaJava contiene el código trabajado
Se agrega carpeta de test

2022-11-25 05:16 UTC, Wizeline-GerardoRuiz approved these changes
LGTM 👍

2022-11-25 05:16 UTC, merged