Se sube Entregable 3 Jonathan Reyes Nava
WIZEACADEMY-BAZ/BAZJAVA_BLOQUE2 pull request #78
Opened 2022-11-21 23:59 UTC by Jona716

2022-11-23 02:29 UTC, Wizeline-GerardoRuiz requested changes

2022-11-23 02:29 UTC, Wizeline-GerardoRuiz commented on Jonathan_Reyes_Nava/Entregable2/.idea/Entregable2.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Dentro de la carpeta donde está este archivo hay demasiados archivos basura que no deben estar, por favor elimínalos para considerar correcta tu entrega

2022-11-23 02:29 UTC, Wizeline-GerardoRuiz commented on Jonathan_Reyes_Nava/Entregable2/learningjavamaven/src/main/java/com/Wizeline/maven/learningjavamaven/batch/BankAccountItemProcessor.java
> +package com.Wizeline.maven.learningjavamaven.batch;public class BankAccountItemProcessor {
Los archivos dentro de esta carpeta están demás y son incorrectos, por favor elimínalos

2022-11-23 02:29 UTC, Wizeline-GerardoRuiz commented on Jonathan_Reyes_Nava/Entregable2/learningjavamaven/src/main/java/com/Wizeline/maven/learningjavamaven/config/BatchConfiguration.java
> +package com.Wizeline.maven.learningjavamaven.config;public class BatchConfiguration {
Este archivo es erróneo, por favor elimínalo

2022-11-23 02:29 UTC, Wizeline-GerardoRuiz commented on Jonathan_Reyes_Nava/Entregable3/learningjavamaven/src/main/java/com/Wizeline/maven/learningjavamaven/PatronesDiseno/Iterator/Channel.java
> +package com.Wizeline.maven.learningjavamaven.PatronesDiseno.Iterator;public class Channel {
Todos los archivos de esta carpeta están vacíos, por favor complétalos para implementar su lógica

2022-11-23 02:29 UTC, Wizeline-GerardoRuiz commented on Jonathan_Reyes_Nava/Entregable3/learningjavamaven/src/main/java/com/Wizeline/maven/learningjavamaven/PatronesDiseno/Singleton/Cliente.java
> +package com.Wizeline.maven.learningjavamaven.PatronesDiseno.Singleton;public class Cliente {
Todos los archivos de esta carpeta están vacíos, por favor complétalos para implementar su lógica

2022-11-23 02:29 UTC, Wizeline-GerardoRuiz commented on Jonathan_Reyes_Nava/Entregable3/learningjavamaven/src/main/java/com/Wizeline/maven/learningjavamaven/PatronesDiseno/Diseno.java
> +package com.Wizeline.maven.learningjavamaven.PatronesDiseno;public class Diseno {
Todos los archivos de esta carpeta están vacíos, por favor complétalos para implementar su lógica

2022-11-25 01:33 UTC, Jona716 commented on Jonathan_Reyes_Nava/Entregable2/.idea/Entregable2.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Se eliminaron los archivos basura que estaban de más.

2022-11-25 01:33 UTC, Jona716 commented on Jonathan_Reyes_Nava/Entregable2/learningjavamaven/src/main/java/com/Wizeline/maven/learningjavamaven/batch/BankAccountItemProcessor.java
> +package com.Wizeline.maven.learningjavamaven.batch;public class BankAccountItemProcessor {
Se eliminaron del Entregable 2.

2022-11-25 01:33 UTC, Jona716 commented on Jonathan_Reyes_Nava/Entregable2/learningjavamaven/src/main/java/com/Wizeline/maven/learningjavamaven/config/BatchConfiguration.java
> +package com.Wizeline.maven.learningjavamaven.config;public class BatchConfiguration {
De igual forma se elimino la clase.

2022-11-25 01:34 UTC, Jona716 commented on Jonathan_Reyes_Nava/Entregable3/learningjavamaven/src/main/java/com/Wizeline/maven/learningjavamaven/PatronesDiseno/Iterator/Channel.java
> +package com.Wizeline.maven.learningjavamaven.PatronesDiseno.Iterator;public class Channel {
Por un error no se subió el archivo completo. Se complementó la lógica de cada archivo.

2022-11-25 01:35 UTC, Jona716 commented on Jonathan_Reyes_Nava/Entregable3/learningjavamaven/src/main/java/com/Wizeline/maven/learningjavamaven/PatronesDiseno/Singleton/Cliente.java
> +package com.Wizeline.maven.learningjavamaven.PatronesDiseno.Singleton;public class Cliente {
Se complementó la lógica de cada archivo.

2022-11-25 01:35 UTC, Jona716 commented on Jonathan_Reyes_Nava/Entregable3/learningjavamaven/src/main/java/com/Wizeline/maven/learningjavamaven/PatronesDiseno/Diseno.java
> +package com.Wizeline.maven.learningjavamaven.PatronesDiseno;public class Diseno {
Se complementó la lógica de cada archivo.

2022-11-25 02:39 UTC, Wizeline-GerardoRuiz approved these changes
LGTM 👍

2022-11-25 02:39 UTC, merged