Entregable N3 V1
WIZEACADEMY-BAZ/BAZJAVA_BLOQUE2 pull request #79
Opened 2022-11-22 03:34 UTC by aramirex

2022-11-23 01:47 UTC, Wizeline-GerardoRuiz requested changes

2022-11-23 01:47 UTC, Wizeline-GerardoRuiz commented on Alejandro_Ramirez_Flores/Entregable3/LoadBalancer/src/main/java/com/codeusingjava/LoadBalancerApplication.java
> +package com.codeusingjava;
Esta aplicación (LoadBalancer) no debe ser incluida en tu entrega, por favor quítala al hacer tu corrección

2022-11-23 01:47 UTC, Wizeline-GerardoRuiz commented on Alejandro_Ramirez_Flores/Entregable3/learningjavagradle/src/main/java/com/wizeline/gradle/learningjavagradle/kafka/Producer.java
> +    public static void main(String[] args) throws InterruptedException {
Tu método main está duplicado, revisa cuál es el que debes tener y elimina el duplicado para considerar la entrega como correcta

2022-11-23 01:47 UTC, Wizeline-GerardoRuiz commented on Alejandro_Ramirez_Flores/Entregable3/learningjavagradle/build.gradle
> +    implementation group: 'org.jacoco', name: 'jacoco-maven-plugin', version: '0.8.3'
Debes terminar la configuración de este plugin para considerar que JaCoCo está configurado correctamente

2022-11-23 16:13 UTC, aramirex commented on Alejandro_Ramirez_Flores/Entregable3/LoadBalancer/src/main/java/com/codeusingjava/LoadBalancerApplication.java
> +package com.codeusingjava;
Aplicación "LoadBalancer" eliminada.

2022-11-23 16:55 UTC, aramirex commented on Alejandro_Ramirez_Flores/Entregable3/learningjavagradle/src/main/java/com/wizeline/gradle/learningjavagradle/kafka/Producer.java
> +    public static void main(String[] args) throws InterruptedException {
Se procede a eliminar método main indicado.

2022-11-23 20:25 UTC, aramirex commented on Alejandro_Ramirez_Flores/Entregable3/learningjavagradle/build.gradle
> +    implementation group: 'org.jacoco', name: 'jacoco-maven-plugin', version: '0.8.3'
Se procede a terminar de configurar

2022-11-24 19:05 UTC, Wizeline-GerardoRuiz approved these changes
LGTM 👍

2022-11-24 19:05 UTC, merged